#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

# Line 1: Box opening with path and git status
[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#6e6a86'
    template = '┌──'

  [[blocks.segments]]
    type = 'path'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#191724'
    background = '#9ccfd8'
    template = '  {{ .Path }} '

    [blocks.segments.properties]
      style = 'full'

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    foreground = '#191724'
    background = '#c4a7e7'
    foreground_templates = [
      "{{ if or (.Working.Changed) (.Staging.Changed) }}#191724{{ end }}"
    ]
    background_templates = [
      "{{ if or (.Working.Changed) (.Staging.Changed) }}#f6c177{{ end }}",
      "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#eb6f92{{ end }}",
      "{{ if gt .Ahead 0 }}#ebbcba{{ end }}",
      "{{ if gt .Behind 0 }}#eb6f92{{ end }}"
    ]
    template = '  {{ .HEAD }}{{ if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '

    [blocks.segments.properties]
      branch_icon = ' '
      commit_icon = '@'
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#c4a7e7'
    foreground_templates = [
      "{{ if or (.Working.Changed) (.Staging.Changed) }}#f6c177{{ end }}"
    ]
    template = ''

# Line 1: Right side with execution time
[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = '#f6c177'
    background = 'transparent'
    template = ' {{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 500

# Line 2: Box closing with prompt character
[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground = '#6e6a86'
    template = '└─'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}#eb6f92{{end}}",
      "{{if eq .Code 0}}#9ccfd8{{end}}"
    ]
    background = 'transparent'
    template = '❯'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}#eb6f92{{end}}",
    "{{if eq .Code 0}}#9ccfd8{{end}}"
  ]
  background = 'transparent'
  template = '❯ '

[secondary_prompt]
  foreground = '#9ccfd8'
  background = 'transparent'
  template = '❯❯ '
